language: python

python: "3.6"

dist: bionic

services:
    - docker

cache:
    - pip
    - npm

before_install:
    - |
      if [ "$TEST" = "server" ]; then
        sudo apt-get update
        sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi3
        docker-compose -f .travis-docker-compose.yml up -d
      fi

install:
    - |
      if [ "$TEST" = "server" ]; then
        cd server && pip install -r dev-requirements.txt && cd ..
      else
        cd client && npm install && cd ..
      fi

jobs:
    include:
        - script: cd server && flake8 && nosetests tests && python manage.py app:initialize_data
          env: TEST=server
          name: "server"
        - script: cd client && node --max_old_space_size=4098 ./node_modules/.bin/grunt build
          name: "client"

