version: "3.2"
services:

  mongo:
    image: mongo:6
    networks:
      - superdesk
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis:
    image: redis:alpine
    networks:
      - superdesk
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    environment:
      - discovery.type=single-node
    networks:
      - superdesk
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  server:
    build: ./server
    depends_on:
      - redis
      - mongo
      - elastic
    environment:
      - WEB_CONCURRENCY=2
      - MONGO_URI=mongodb://mongo/superdesk
      - CONTENTAPI_MONGO_URI=mongodb://mongo/superdesk_capi
      - PUBLICAPI_MONGO_URI=mongodb://mongo/superdesk_papi
      - LEGAL_ARCHIVE_URI=mongodb://mongo/superdesk_legal
      - ARCHIVED_URI=mongodb://mongo/superdesk_archive
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_INDEX=superdesk
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      - DEFAULT_TIMEZONE=Europe/Prague
      - SECRET_KEY=*k^&9)byk=8en9n1sg7-xj4f8wr2mh^x#t%_2=1=z@69oxt50!
      # More configuration options can be found at https://superdesk.readthedocs.io/en/latest/settings.html
    networks:
      - superdesk
    ports:
      - "5000:5000"
      - "5100:5100"
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /opt/superdesk
          ignore:
            - env/
            - requirements.txt

  client:
    build: ./client
    ports:
      - "9000:9000"
    networks:
      - superdesk
    develop:
      watch:
        - action: sync
          path: ./client
          target: /opt/client
          ignore:
            - node_modules/

networks:
    superdesk:
        driver: bridge

volumes:
  mongo:
  elastic:
