rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker -X "${SUPERDESK_CELERY_PREFIX}expiry" worker
beat: celery -A worker beat --pid=
prod_api: gunicorn -c gunicorn_config.py prod_api_app
work_expiry: celery -A worker -Q "${SUPERDESK_CELERY_PREFIX}expiry" -c 2 worker
